### ISSUE TITLE
How do I find the Column Id? (as workaround for 2k limit)

### ISSUE THREAD

**Issue by ywang63** [phelipetls/reportforce#8]
Hi, thanks for sharing your work. I am just not sure how do I find the case number for column ID? Could you provide guide?

**Comment by phelipetls** [comment]
Hi, glad you find it useful.

To make the workaround work, you will need to pass any column which has a unique value per row, acting as an identifier for each row. That's the only way to overcome the limitation.

It can be any column which qualify as such. It has to be in the report though, because we will have to get its values and exclude them from the next report, to get new rows.

Sorry for the confusion, maybe I'll have to improve the documentation. Where did you get confused by this?
